mapping:
    -   boxID:      sepp
        name:       sepp
        sensors:
            -   type:   1
                id:     5b14eda64cd32e00195ec2cd
            -   type:   2
                id:     5b14eda64cd32e00195ec2cc
            -   type:   3
                id:     5b14eda64cd32e00195ec2cb
    -   boxID:      hans
        name:       hans
        sensors:
            -   type:   1
                id:     5b14eda64cd32e00195ec2cc
            -   type:   3
                id:     5b14eda64cd32e00195ec2ca
    -   boxID:      massimo
        name:       massimo
        sensors:
            -   type:   1
                id:     5b14eda64cd32e00195ec2cc
            -   type:   3
                id:     5b14eda64cd32e00195ec2ca
    -   boxID:      dorian
        name:       dorian
        sensors:
            -   type:   1
                id:     5b14eda64cd32e00195ec2cc
            -   type:   3
                id:     5b14eda64cd32e00195ec2ca
    -   boxID:      lukas
        name:       lukas
        sensors:
            -   type:   1
                id:     5b14eda64cd32e00195ec2cc
            -   type:   3
                id:     5b14eda64cd32e00195ec2ca